version = 0.1

[default.deploy.parameters]
stack_name = "calculator-app"
resolve_s3 = true
s3_prefix = "calculator-app"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ImageUri=156041404525.dkr.ecr.ap-south-1.amazonaws.com/my-calculator-app:106"
