AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ImageTag:
    Type: String
    Description: The Docker image tag for the Lambda function
  ECR_REPO_NAME:
    Type: String
    Description: The ECR repository name for the Lambda function
  ECR_REGISTRY:
    Type: String
    Description: The ECR registry URI for the Lambda function

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Sub "${ECR_REGISTRY}/${ECR_REPO_NAME}:${ImageTag}"
      Timeout: 30
      MemorySize: 128
