AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ImageTag:
    Type: String
    Default: "latest"
    Description: "The tag of the Docker image for the Lambda function"

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-lambda-function
      PackageType: Image
      ImageUri: !Sub "156041404525.dkr.ecr.${AWS::Region}.amazonaws.com/my-calculator-app:${ImageTag}"
      MemorySize: 512
      Timeout: 60
