AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  ImageTag:
    Type: String
    Description: The Docker image tag for the Lambda function
  ECRRepoName:
    Type: String
    Description: The ECR repository name for the Lambda function
  ECRRegistry:
    Type: String
    Description: The ECR registry URI for the Lambda function

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Sub "${ECRRegistry}/${ECRRepoName}:${ImageTag}"
      Timeout: 30
      MemorySize: 128
